// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package pb2json_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemFeature struct {
	ItemFeature          []byte   `protobuf:"bytes,1,opt,name=item_feature,json=itemFeature,proto3" json:"item_feature,omitempty"`
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemFeature) Reset()         { *m = ItemFeature{} }
func (m *ItemFeature) String() string { return proto.CompactTextString(m) }
func (*ItemFeature) ProtoMessage()    {}
func (*ItemFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *ItemFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemFeature.Unmarshal(m, b)
}
func (m *ItemFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemFeature.Marshal(b, m, deterministic)
}
func (m *ItemFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemFeature.Merge(m, src)
}
func (m *ItemFeature) XXX_Size() int {
	return xxx_messageInfo_ItemFeature.Size(m)
}
func (m *ItemFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemFeature.DiscardUnknown(m)
}

var xxx_messageInfo_ItemFeature proto.InternalMessageInfo

func (m *ItemFeature) GetItemFeature() []byte {
	if m != nil {
		return m.ItemFeature
	}
	return nil
}

func (m *ItemFeature) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*ItemFeature)(nil), "pb2json.api.ItemFeature")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2c, 0x49, 0xcd,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2e, 0x48, 0x32, 0xca, 0x2a, 0xce, 0xcf, 0xd3,
	0x4b, 0x2c, 0xc8, 0x54, 0xf2, 0xe2, 0xe2, 0xf6, 0x2c, 0x49, 0xcd, 0x75, 0x4b, 0x4d, 0x2c, 0x29,
	0x2d, 0x4a, 0x15, 0x52, 0xe4, 0xe2, 0x01, 0xa9, 0x8c, 0x4f, 0x83, 0xf0, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x78, 0x82, 0xb8, 0x33, 0x91, 0x94, 0x48, 0x70, 0xb1, 0x97, 0xa5, 0x16, 0x15, 0x67, 0xe6,
	0xe7, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xb8, 0x49, 0x6c, 0x60, 0xf3, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x64, 0x59, 0xc7, 0x6d, 0x00, 0x00, 0x00,
}
